version: 2.1

orbs:
  my-orb:
    executors:
      specialthingsexecutor:
        docker:
          - image: alpine:3.7
    commands:
      dospecialthings:
        steps:
          - run: echo "We will now do special things"
    jobs:
      myjob:
        executor: specialthingsexecutor
        parameters:
          extra_steps:
            description: Extra steps to execute
            type: steps
            default: []
        steps:
          - dospecialthings

jobs:
 build:
   docker:
     - image: alpine:3.7
   steps:
     - my-orb/dospecialthings

