version: 2.0

jobs:
 build:
   docker:
    - image: alpine:3.7
   steps:
    - run:
        name: Install Base Software
        command: |
          apk add git
          wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz -O hugo.tar.gz
          tar -C /bin -xvzf hugo.tar.gz
          rm -rf /tmp/site
          rm -rf /root/project
    - checkout
    - run: ls
    - run: pwd
    - run: hugo -d /tmp/site
   persist_to_workspace:
    root: /tmp
    paths:
      - site

