version: 2.1

orbs:
  my-orb:
    executors:
      specialthingsexecutor:
        docker:
          - image: alpine:3.7
    commands:
      dospecialthings:
        steps:
          - run: echo "We will now do special things"
    jobs:
      myjob:
        executor: specialthingsexecutor
        steps:
          - dospecialthings

workflows:
  main:
    jobs:
      - my-orb/myjob