version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: Install Base Software
          command: |
            wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz -O /tmp/hugo.tar.gz
            tar -C /tmp -xvzf /tmp/hugo.tar.gz
      - checkout
      - run:
          name: Build site
          command: /tmp/hugo
      - persist_to_workspace:
          root: .
          paths:
            - public/
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install Base Software
          command: |
            pip install --user awscli
      - run:
          name: Deploy
          command: |
            export PATH=$PATH:/home/circleci/.local/bin
            aws s3 sync /tmp/workspace/public s3://miguelgarcia.dev-site

workflows:
  version: 2.1
  default:
    triggers:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master