version: 2.1

orbs:
  my-orb:
    executors:
      myexecutor:
        docker:
          - image: alpine:3.7
    jobs:
      myjob:
        description: an orb job
        executor: myexecutor
        parameters:
          something:
            description: For example a key
            type: string
            default: BLABLA
          work_steps:
            description: Steps to execute
            type: steps
            default: []
        steps:
          - run:
            name: Check My IP
            command: |
              apk add curl
              echo Hola
          - when:
            name: Run work steps.
            condition: << parameters.work_steps >>
            steps: << parameters.work_steps >>


workflows:
  main:
    jobs:
      - my-orb/myjob